blank_issues_enabled: false
contact_links:
  - name: Relatar uma vulnerabilidade
    url: https://github.com/arcanTi/limiar-os/security/advisories/new
    about: Envie vulnerabilidades de forma privada aos mantenedores.
