import { sessionUsername } from '../domain/campaigns/index.ts';
import { effectiveMoveStat } from '../domain/character/derivedStatsEngine.ts';
import { cellKey, cellsToMeters, GRID_METERS_PER_CELL, moveRangePixels, segmentMovementCost } from '../domain/movement/index.ts';
import { createLimiarAPI } from '../infrastructure/api/index.ts';
import { getToken } from '../infrastructure/session.ts';

"use strict";
const limiarApi = createLimiarAPI();
const params = new URLSearchParams(location.search);
const campaignId = params.get("campaign") || "";
const state = { session:null, canEdit:false, scene:null, scenes:[], tokens:[], fogAreas:[], reveals:[], selected:null, tool:"select", showGrid:true, snap:false, runMode:false, camera:{x:0,y:0,zoom:1}, mapImage:null, tokenImages:new Map(), measure:null, fogDraft:null, difficultCells:new Set(), characterMoveCache:new Map(), selectedMoveCells:null };
const canvas = byId("canvas"), ctx = canvas.getContext("2d");
const ui = {
  sceneName:byId("sceneName"), campaignName:byId("campaignName"), hud:byId("hud"), status:byId("statusText"), sceneSelect:byId("sceneSelect"), sceneInput:byId("sceneInput"), bgInput:byId("bgInput"), fitSelect:byId("fitSelect"), gridInput:byId("gridInput"), widthInput:byId("widthInput"), heightInput:byId("heightInput"), uploadFile:byId("uploadFile"), tokenList:byId("tokenList"), fogList:byId("fogList"), tokenName:byId("tokenName"), tokenColor:byId("tokenColor"), tokenImage:byId("tokenImage"), tokenSize:byId("tokenSize"), tokenVision:byId("tokenVision"), tokenMove:byId("tokenMove"), tokenHp:byId("tokenHp"), tokenHpMax:byId("tokenHpMax"), tokenVisible:byId("tokenVisible"), tokenUploadFile:byId("tokenUploadFile"), gridToggle:byId("gridToggle"), snapToggle:byId("snapToggle"), runToggle:byId("runToggle")
};
const pointer = { down:false, mode:"", id:null, start:{x:0,y:0}, world:{x:0,y:0}, cam:{x:0,y:0}, offset:{x:0,y:0}, terrainTouched:null };
let terrainQueue = Promise.resolve();
let raf = 0;
function byId(id){return document.getElementById(id)}
function esc(v){return String(v == null ? "" : v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function status(text,kind=""){ui.status.textContent=text;ui.status.className="status "+kind}
function runAction(fn){return async()=>{try{await fn()}catch(e){status(e.message||"acao indisponivel","err")}}}
function canMove(t){return state.canEdit || t.ownerUsername === sessionUsername(state.session)}
function sceneSize(){return {w:Number(state.scene&&state.scene.width||1600),h:Number(state.scene&&state.scene.height||1000),g:Number(state.scene&&state.scene.gridSize||64)}}
async function init(){bind();resize();if(!campaignId)return status("campanha ausente na URL","err");if(!getToken())return status("login necessario","err");state.session = await limiarApi.auth.session().then(d=>d.user||d);await load();fitView();setInterval(loadSoft,4000)}
async function load(){const data=await limiarApi.campaignMaps.get(campaignId);state.canEdit=!!data.canEdit;state.scene=data.scene;state.scenes=data.scenes||[];state.tokens=data.tokens||[];state.fogAreas=data.fogAreas||[];state.reveals=data.reveals||[];state.difficultCells=new Set((data.scene&&data.scene.difficultTerrain||[]).map(([x,y])=>cellKey(x,y)));applyScene();renderScenes();renderTokens();renderFog();loadMapImage();updateSelectedMove();drawOnce()}
async function loadSoft(){try{const sel=state.selected;await load();state.selected=sel&&state.tokens.some(t=>t.id===sel)?sel:state.selected;renderTokens()}catch(_){}}
function applyScene(){const s=state.scene||{};ui.sceneName.textContent=s.name||"Cena";ui.campaignName.textContent=campaignId;ui.sceneInput.value=s.name||"";ui.bgInput.value=s.background||"";ui.fitSelect.value=s.backgroundFit||"contain";ui.gridInput.value=s.gridSize||64;ui.widthInput.value=s.width||1600;ui.heightInput.value=s.height||1000;document.querySelectorAll(".master-only").forEach(el=>el.hidden=!state.canEdit)}
function renderScenes(){ui.sceneSelect.innerHTML=state.scenes.map(s=>`<option value="${esc(s.id)}" ${s.active?"selected":""}>${s.active?"* ":""}${esc(s.name)}</option>`).join("")}
function loadMapImage(){state.mapImage=null;const src=state.scene&&state.scene.background;if(!src){drawOnce();return}const img=new Image();img.onload=()=>{state.mapImage=img;drawOnce()};img.onerror=()=>status("imagem do mapa nao carregou","err");img.src=src}
function resize(){const r=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(320,Math.floor(r.width*dpr));canvas.height=Math.max(240,Math.floor(r.height*dpr));ctx.setTransform(dpr,0,0,dpr,0,0);drawOnce()}
function fitView(){const r=canvas.getBoundingClientRect(),{w,h}=sceneSize();const z=Math.max(.05,Math.min(4,Math.min(r.width/w,r.height/h)*.94));state.camera.zoom=z;state.camera.x=(r.width-w*z)/2;state.camera.y=(r.height-h*z)/2;drawOnce()}
function screenToWorld(x,y){const r=canvas.getBoundingClientRect();return {x:(x-r.left-state.camera.x)/state.camera.zoom,y:(y-r.top-state.camera.y)/state.camera.zoom}}
function snap(p){if(!state.snap)return p;const g=sceneSize().g;return {x:Math.round(p.x/g)*g,y:Math.round(p.y/g)*g}}
function tokenRadius(t){return Math.max(14,sceneSize().g*.36*Number(t.size||1))}
function tokenAt(p){for(let i=state.tokens.length-1;i>=0;i--){const t=state.tokens[i];if(t.visible===false&&!state.canEdit)continue;if(Math.hypot(t.x-p.x,t.y-p.y)<=Math.max(tokenRadius(t),18/state.camera.zoom))return t}return null}
function bgPlacement(){const {w,h}=sceneSize(),img=state.mapImage,mode=(state.scene&&state.scene.backgroundFit)||"contain";if(!img||mode==="stretch")return{x:0,y:0,w,h};if(mode==="native")return{x:(w-img.naturalWidth)/2,y:(h-img.naturalHeight)/2,w:img.naturalWidth,h:img.naturalHeight};const ratio=mode==="cover"?Math.max(w/img.naturalWidth,h/img.naturalHeight):Math.min(w/img.naturalWidth,h/img.naturalHeight);return{x:(w-img.naturalWidth*ratio)/2,y:(h-img.naturalHeight*ratio)/2,w:img.naturalWidth*ratio,h:img.naturalHeight*ratio}}
function tokenImage(src){if(!src)return null;let img=state.tokenImages.get(src);if(img)return img.ready?img:null;img=new Image();img.ready=false;img.onload=()=>{img.ready=true;drawOnce()};img.onerror=()=>state.tokenImages.delete(src);img.src=src;state.tokenImages.set(src,img);return null}
function drawOnce(){cancelAnimationFrame(raf);raf=requestAnimationFrame(draw)}
function draw(){const r=canvas.getBoundingClientRect(),{w,h,g}=sceneSize();ctx.clearRect(0,0,r.width,r.height);ctx.save();ctx.translate(state.camera.x,state.camera.y);ctx.scale(state.camera.zoom,state.camera.zoom);ctx.fillStyle="#050706";ctx.fillRect(0,0,w,h);if(state.mapImage){const b=bgPlacement();ctx.save();ctx.beginPath();ctx.rect(0,0,w,h);ctx.clip();ctx.drawImage(state.mapImage,b.x,b.y,b.w,b.h);ctx.restore()}else{ctx.fillStyle="#10170f";ctx.fillRect(0,0,w,h)}if(state.showGrid)drawGrid(w,h,g);drawDifficultTerrain(g);ctx.strokeStyle="rgba(214,170,78,.65)";ctx.lineWidth=3/state.camera.zoom;ctx.strokeRect(0,0,w,h);state.tokens.filter(t=>state.canEdit||t.visible!==false).forEach(drawToken);drawMoveRange(g);drawShadow(w,h);drawManualFog();drawMeasure(g);ctx.restore();const moveLabel=state.selectedMoveCells!=null?` | MOVE ${state.selectedMoveCells}q${state.runMode?" (RUN x2)":""}`:"";ui.hud.textContent=`Zoom ${Math.round(state.camera.zoom*100)}% | Grid ${g}px (${GRID_METERS_PER_CELL}m) | ${state.tool}${moveLabel}`}
function drawDifficultTerrain(g){if(!state.difficultCells.size)return;ctx.save();ctx.fillStyle="rgba(192,99,91,.24)";ctx.strokeStyle="rgba(192,99,91,.55)";ctx.lineWidth=1/state.camera.zoom;state.difficultCells.forEach(key=>{const [gx,gy]=key.split(",").map(Number);ctx.fillRect(gx*g,gy*g,g,g);ctx.strokeRect(gx*g,gy*g,g,g)});ctx.restore()}
// Overlay informativo de alcance de movimento (CPR RAW: MOVE x 2m; Run dobra
// a distancia). So desenha, nao bloqueia o drag do token — o GM arbitra.
function drawMoveRange(g){if(state.selectedMoveCells==null)return;const t=state.tokens.find(x=>x.id===state.selected);if(!t)return;const radius=moveRangePixels(state.selectedMoveCells,g,{run:state.runMode});if(!radius)return;ctx.save();ctx.strokeStyle="rgba(63,224,208,.5)";ctx.setLineDash([6/state.camera.zoom,5/state.camera.zoom]);ctx.lineWidth=2/state.camera.zoom;ctx.beginPath();ctx.arc(t.x,t.y,radius,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);ctx.restore()}
function drawGrid(w,h,g){ctx.strokeStyle="rgba(214,170,78,.14)";ctx.lineWidth=1/state.camera.zoom;ctx.beginPath();for(let x=0;x<=w;x+=g){ctx.moveTo(x,0);ctx.lineTo(x,h)}for(let y=0;y<=h;y+=g){ctx.moveTo(0,y);ctx.lineTo(w,y)}ctx.stroke()}
function drawToken(t){const r=tokenRadius(t),sel=t.id===state.selected,img=tokenImage(t.image);ctx.save();ctx.translate(t.x,t.y);ctx.fillStyle=t.color||"#d6aa4e";ctx.shadowColor="rgba(0,0,0,.58)";ctx.shadowBlur=16/state.camera.zoom;ctx.beginPath();ctx.arc(0,0,r,0,Math.PI*2);ctx.fill();ctx.shadowColor="transparent";if(img){ctx.save();ctx.beginPath();ctx.arc(0,0,r*.92,0,Math.PI*2);ctx.clip();const side=Math.min(img.naturalWidth,img.naturalHeight),sx=(img.naturalWidth-side)/2,sy=(img.naturalHeight-side)/2;ctx.drawImage(img,sx,sy,side,side,-r*.92,-r*.92,r*1.84,r*1.84);ctx.restore()}else{ctx.fillStyle="rgba(0,0,0,.48)";ctx.beginPath();ctx.arc(0,0,r*.72,0,Math.PI*2);ctx.fill();ctx.fillStyle="#fff";ctx.textAlign="center";ctx.textBaseline="middle";ctx.font=`${Math.max(12,r*.45)}px monospace`;ctx.fillText((t.name||"?").split(/\s+/).slice(0,2).map(x=>x[0]).join("").toUpperCase(),0,0)}ctx.lineWidth=(sel?5:2)/state.camera.zoom;ctx.strokeStyle=sel?varColor("--teal"):"rgba(5,7,6,.94)";ctx.stroke();drawName(t,r);if(t.kind==="player")drawHp(t,r);if(state.canEdit&&Number(t.vision)>0){ctx.strokeStyle="rgba(63,224,208,.16)";ctx.lineWidth=1/state.camera.zoom;ctx.beginPath();ctx.arc(0,0,Number(t.vision),0,Math.PI*2);ctx.stroke()}ctx.restore()}
function drawName(t,r){const label=t.name||"Token";ctx.font=`${12/state.camera.zoom}px monospace`;const mw=ctx.measureText(label).width+12/state.camera.zoom,mh=22/state.camera.zoom;ctx.fillStyle="rgba(0,0,0,.76)";roundRect(-mw/2,r+6/state.camera.zoom,mw,mh,5/state.camera.zoom);ctx.fill();ctx.fillStyle="#fff";ctx.textAlign="center";ctx.textBaseline="top";ctx.fillText(label,0,r+11/state.camera.zoom)}
function drawHp(t,r){if(t.hp==null||t.hpMax==null||!t.hpMax)return;const pct=Math.max(0,Math.min(1,Number(t.hp)/Number(t.hpMax)));ctx.strokeStyle="rgba(0,0,0,.72)";ctx.lineWidth=6/state.camera.zoom;ctx.beginPath();ctx.arc(0,0,r+7/state.camera.zoom,-Math.PI/2,Math.PI*1.5);ctx.stroke();ctx.strokeStyle=pct>.5?"#3fe0d0":pct>.25?"#d6aa4e":"#c0635b";ctx.beginPath();ctx.arc(0,0,r+7/state.camera.zoom,-Math.PI/2,-Math.PI/2+Math.PI*2*pct);ctx.stroke()}
function drawShadow(w,h){if(!state.scene||!state.scene.fogEnabled)return;const tokens=state.tokens.filter(t=>t.visible!==false&&Number(t.vision)>0&&(state.canEdit||t.kind==="player"));ctx.save();ctx.fillStyle=`rgba(0,0,0,${state.canEdit ? .38 : (state.scene.shadowOpacity||.92)})`;ctx.fillRect(0,0,w,h);ctx.globalCompositeOperation="destination-out";for(const r of state.reveals){clearVision(r.x,r.y,r.radius)}for(const t of tokens){clearVision(t.x,t.y,Number(t.vision))}ctx.restore()}
function clearVision(x,y,radius){const rg=ctx.createRadialGradient(x,y,Math.max(10,Number(radius)*.24),x,y,Number(radius));rg.addColorStop(0,"rgba(0,0,0,1)");rg.addColorStop(.72,"rgba(0,0,0,.82)");rg.addColorStop(1,"rgba(0,0,0,0)");ctx.fillStyle=rg;ctx.beginPath();ctx.arc(x,y,Number(radius),0,Math.PI*2);ctx.fill()}
function drawManualFog(){ctx.save();for(const f of state.fogAreas){ctx.fillStyle=state.canEdit?"rgba(0,0,0,.46)":"rgba(0,0,0,.98)";ctx.fillRect(f.x,f.y,f.width,f.height);if(state.canEdit){ctx.strokeStyle="rgba(214,170,78,.72)";ctx.lineWidth=2/state.camera.zoom;ctx.strokeRect(f.x,f.y,f.width,f.height)}}if(state.fogDraft){const f=state.fogDraft;ctx.fillStyle="rgba(63,224,208,.16)";ctx.strokeStyle="#3fe0d0";ctx.lineWidth=2/state.camera.zoom;ctx.fillRect(f.x,f.y,f.width,f.height);ctx.strokeRect(f.x,f.y,f.width,f.height)}ctx.restore()}
function drawMeasure(g){if(!state.measure)return;const {from,to}=state.measure,cost=segmentMovementCost(from,to,g,state.difficultCells);ctx.strokeStyle="#d6aa4e";ctx.lineWidth=3/state.camera.zoom;ctx.setLineDash([8/state.camera.zoom,7/state.camera.zoom]);ctx.beginPath();ctx.moveTo(from.x,from.y);ctx.lineTo(to.x,to.y);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle="#d6aa4e";ctx.font=`${14/state.camera.zoom}px monospace`;const terrainLabel=cost.difficultCellCount?` // custo ${cost.costCells}q // ${cost.costMeters.toFixed(0)}m (terreno dificil)`:"";ctx.fillText(`${cost.cellCount}q // ${cellsToMeters(cost.cellCount).toFixed(0)}m${terrainLabel}`,(from.x+to.x)/2,(from.y+to.y)/2)}
function roundRect(x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath()}
function varColor(name){return getComputedStyle(document.documentElement).getPropertyValue(name).trim()}
function renderTokens(){ui.tokenList.innerHTML=state.tokens.map(t=>`<button class="list-btn token-row ${t.id===state.selected?"active":""}" data-token="${esc(t.id)}"><span class="swatch" style="background:${esc(t.color)}"></span><span>${esc(t.name)}<br><small class="tag">${esc(t.kind)} ${t.ownerUsername?"// "+esc(t.ownerUsername):""}</small></span><span class="tag">${Number(t.vision||0)}px</span>${state.canEdit?`<span class="tag danger" data-remove-token="${esc(t.id)}">remover</span>`:""}</button>`).join("")||'<p class="hint">sem tokens</p>'}
function renderFog(){ui.fogList.innerHTML=state.fogAreas.map(f=>`<button class="list-btn"><span>${esc(f.label)}<br><small class="tag">${Math.round(f.width)} x ${Math.round(f.height)}</small></span>${state.canEdit?`<span class="tag danger" data-remove-fog="${esc(f.id)}">revelar</span>`:""}</button>`).join("")||'<p class="hint">nenhuma area</p>'}
function syncTokenForm(){const t=state.tokens.find(x=>x.id===state.selected);if(!t)return;ui.tokenName.value=t.name||"";ui.tokenColor.value=t.color||"#d6aa4e";ui.tokenImage.value=t.image||"";ui.tokenSize.value=t.size||1;ui.tokenVision.value=t.vision||0;ui.tokenMove.value=t.move==null?"":t.move;ui.tokenMove.disabled=!!t.characterId;ui.tokenHp.value=t.hp==null?"":t.hp;ui.tokenHpMax.value=t.hpMax==null?"":t.hpMax;ui.tokenVisible.checked=t.visible!==false}
// MOVE efetivo do token selecionado (CPR RAW: base MOVE - penalidade de
// armadura - movePenalty de conditions, ja agregados em effectiveMoveStat).
// Token vinculado a personagem busca a ficha (so o dono ou o GM podem, ver
// permissao de /characters/:id); token sem personagem usa o campo manual
// `move` (default 6). Cacheado por characterId para nao refazer fetch a cada
// redraw.
async function updateSelectedMove(){const t=state.tokens.find(x=>x.id===state.selected);if(!t){state.selectedMoveCells=null;drawOnce();return}if(!t.characterId){state.selectedMoveCells=Number(t.move||6);drawOnce();return}if(state.characterMoveCache.has(t.characterId)){state.selectedMoveCells=state.characterMoveCache.get(t.characterId);drawOnce();return}try{const character=await limiarApi.characters.get(t.characterId);const move=effectiveMoveStat(character);state.characterMoveCache.set(t.characterId,move);state.selectedMoveCells=move}catch(_){state.selectedMoveCells=Number(t.move||6)}drawOnce()}
async function saveScene(activate=false){const payload={id:activate?ui.sceneSelect.value:(state.scene&&state.scene.id),name:ui.sceneInput.value||"Cena",background:ui.bgInput.value,backgroundFit:ui.fitSelect.value,width:Number(ui.widthInput.value||1600),height:Number(ui.heightInput.value||1000),gridSize:Number(ui.gridInput.value||64),fogEnabled:true,shadowOpacity:Number((state.scene&&state.scene.shadowOpacity)||.92),activate};await limiarApi.campaignMaps.saveScene(campaignId,payload);await load();status("cenario salvo","ok")}
async function newScene(){const name=prompt("Nome da cena","Nova cena");if(!name)return;await limiarApi.campaignMaps.saveScene(campaignId,{name,activate:true});await load();fitView()}
async function activateScene(){await limiarApi.campaignMaps.activate(campaignId,ui.sceneSelect.value);await load();fitView()}
async function uploadImage(file,scope){return limiarApi.uploads.image(file,{scope,ownerId:campaignId})}
function readImageSize(src){return new Promise(res=>{if(!src)return res(null);const img=new Image();img.onload=()=>res({w:img.naturalWidth,h:img.naturalHeight});img.onerror=()=>res(null);img.src=src})}
async function uploadMap(){const file=ui.uploadFile.files[0];if(!file)return;try{status(`enviando mapa: ${file.name}`);const asset=await uploadImage(file,"campaign-map");ui.bgInput.value=asset.url;const size=await readImageSize(asset.url);if(size){ui.widthInput.value=size.w;ui.heightInput.value=size.h}await saveScene();status("imagem do mapa enviada e salva","ok")}catch(e){status(`falha no upload do mapa: ${e.message}`,"err")}finally{ui.uploadFile.value=""}}
async function uploadToken(){const file=ui.tokenUploadFile.files[0];if(!file)return;try{status(`enviando token: ${file.name}`);const asset=await uploadImage(file,"campaign-token");ui.tokenImage.value=asset.url;await saveToken();status("token atualizado","ok")}catch(e){status(`falha no upload do token: ${e.message}`,"err")}finally{ui.tokenUploadFile.value=""}}
async function useImageSize(){const src=ui.bgInput.value;if(!src)return status("informe uma imagem primeiro","err");const size=await readImageSize(src);if(size){ui.widthInput.value=size.w;ui.heightInput.value=size.h;await saveScene();return}status("nao consegui ler o tamanho da imagem","err")}
async function saveToken(){if(!state.canEdit)return;const old=state.tokens.find(t=>t.id===state.selected),r=canvas.getBoundingClientRect(),c=snap(screenToWorld(r.left+r.width/2,r.top+r.height/2));const payload={id:old&&old.id,name:ui.tokenName.value||"Token",kind:old&&old.kind||"npc",characterId:old&&old.characterId,ownerUsername:old&&old.ownerUsername,x:old?old.x:c.x,y:old?old.y:c.y,color:ui.tokenColor.value,size:Number(ui.tokenSize.value||1),vision:Number(ui.tokenVision.value||0),move:(old&&old.characterId)||ui.tokenMove.value===""?null:Number(ui.tokenMove.value),image:ui.tokenImage.value,hp:ui.tokenHp.value===""?null:Number(ui.tokenHp.value),hpMax:ui.tokenHpMax.value===""?null:Number(ui.tokenHpMax.value),visible:ui.tokenVisible.checked};const saved=await limiarApi.campaignMaps.saveToken(campaignId,payload);state.selected=saved.id;await load();status("token salvo","ok")}
async function syncPlayers(){const d=await limiarApi.campaignMaps.syncPlayers(campaignId);await load();status(`tokens criados/atualizados: ${d.players}`,"ok")}
async function moveToken(t){await limiarApi.campaignMaps.moveToken(campaignId,{tokenId:t.id,x:t.x,y:t.y})}
async function deleteToken(id){if(!state.canEdit||!confirm("Remover token?"))return;await limiarApi.campaignMaps.deleteToken(campaignId,id);await load();status("token removido","ok")}
async function saveFog(f){if(!state.canEdit||f.width<8||f.height<8)return;await limiarApi.campaignMaps.saveFog(campaignId,f);await load()}
async function deleteFog(id){if(!state.canEdit)return;await limiarApi.campaignMaps.deleteFog(campaignId,id);await load();status("area revelada","ok")}
async function clearReveals(){if(!state.canEdit||!confirm("Resetar areas ja reveladas desta cena?"))return;await limiarApi.campaignMaps.clearReveals(campaignId);await load();status("exploracao resetada","ok")}
// Pinta/apaga terreno dificil por celula (CPR RAW: 2m gastos por 1m
// percorrido). Um toggle por celula por arraste (pointer.terrainTouched) pra
// nao alternar ida-e-volta ao passar o mouse repetidas vezes na mesma celula.
// Cada toggle e' um read-modify-write no backend (le a lista, altera, salva) —
// encadeado em terrainQueue pra nao rodar dois toggles em paralelo e um
// sobrescrever o outro quando o arraste passa por varias celulas rapido.
function toggleTerrainAtWorld(p){if(!pointer.terrainTouched)return;const g=sceneSize().g,gx=Math.floor(p.x/g),gy=Math.floor(p.y/g),key=cellKey(gx,gy);if(pointer.terrainTouched.has(key))return;pointer.terrainTouched.add(key);terrainQueue=terrainQueue.then(()=>limiarApi.campaignMaps.toggleTerrain(campaignId,{x:gx,y:gy})).then(scene=>{state.scene=scene;state.difficultCells=new Set((scene.difficultTerrain||[]).map(([x,y])=>cellKey(x,y)));drawOnce()}).catch(e=>status(e.message||"terreno indisponivel","err"))}
async function clearTerrain(){if(!state.canEdit||!confirm("Limpar todo terreno dificil desta cena?"))return;const scene=await limiarApi.campaignMaps.clearTerrain(campaignId);state.scene=scene;state.difficultCells=new Set();drawOnce();status("terreno dificil limpo","ok")}
function zoom(delta,cx=canvas.getBoundingClientRect().width/2,cy=canvas.getBoundingClientRect().height/2){const before=screenToWorld(cx+canvas.getBoundingClientRect().left,cy+canvas.getBoundingClientRect().top);state.camera.zoom=Math.max(.05,Math.min(5,state.camera.zoom+delta));state.camera.x=cx-before.x*state.camera.zoom;state.camera.y=cy-before.y*state.camera.zoom;drawOnce()}
function setTool(tool){state.tool=tool;document.querySelectorAll("[data-tool]").forEach(b=>b.classList.toggle("active",b.dataset.tool===tool));drawOnce()}
function centerToken(){const t=state.tokens.find(x=>x.id===state.selected);if(!t)return;const r=canvas.getBoundingClientRect();state.camera.x=r.width/2-t.x*state.camera.zoom;state.camera.y=r.height/2-t.y*state.camera.zoom;drawOnce()}
function bind(){addEventListener("resize",resize);byId("backBtn").onclick=()=>location.href="/";byId("reloadBtn").onclick=runAction(load);byId("fitBtn").onclick=fitView;byId("fitPanelBtn").onclick=fitView;byId("centerBtn").onclick=fitView;byId("zoomInBtn").onclick=()=>zoom(.15);byId("zoomOutBtn").onclick=()=>zoom(-.15);byId("sideBtn").onclick=()=>document.body.classList.toggle("side-off");byId("sideCloseBtn").onclick=()=>document.body.classList.add("side-off");byId("saveSceneBtn").onclick=runAction(()=>saveScene());byId("newSceneBtn").onclick=runAction(newScene);byId("activateSceneBtn").onclick=runAction(activateScene);ui.uploadFile.onchange=runAction(uploadMap);byId("useImageSizeBtn").onclick=runAction(useImageSize);byId("addTokenBtn").onclick=runAction(async()=>{state.selected=null;await saveToken()});byId("saveTokenBtn").onclick=runAction(saveToken);byId("centerTokenBtn").onclick=centerToken;byId("syncPlayersBtn").onclick=runAction(syncPlayers);ui.tokenUploadFile.onchange=runAction(uploadToken);byId("fogToolBtn").onclick=()=>setTool("fog");byId("clearRevealsBtn").onclick=runAction(clearReveals);byId("clearTerrainBtn").onclick=runAction(clearTerrain);ui.gridToggle.onchange=()=>{state.showGrid=ui.gridToggle.checked;drawOnce()};ui.snapToggle.onchange=()=>state.snap=ui.snapToggle.checked;ui.runToggle.onchange=()=>{state.runMode=ui.runToggle.checked;drawOnce()};document.querySelectorAll("[data-tool]").forEach(b=>b.onclick=()=>setTool(b.dataset.tool));document.querySelectorAll("[data-panel]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-panel]").forEach(x=>x.classList.toggle("active",x===b));document.querySelectorAll(".panel").forEach(p=>p.classList.toggle("active",p.id==="panel-"+b.dataset.panel))});ui.tokenList.onclick=e=>{const rm=e.target.closest("[data-remove-token]");if(rm){runAction(()=>deleteToken(rm.dataset.removeToken))();return}const btn=e.target.closest("[data-token]");if(btn){state.selected=btn.dataset.token;syncTokenForm();renderTokens();updateSelectedMove();drawOnce()}};ui.fogList.onclick=e=>{const rm=e.target.closest("[data-remove-fog]");if(rm)runAction(()=>deleteFog(rm.dataset.removeFog))()};canvas.addEventListener("wheel",e=>{e.preventDefault();const r=canvas.getBoundingClientRect();zoom(e.deltaY>0?-.12:.12,e.clientX-r.left,e.clientY-r.top)},{passive:false});canvas.addEventListener("contextmenu",e=>e.preventDefault());canvas.addEventListener("mousedown",onDown);addEventListener("mousemove",onMove);addEventListener("mouseup",onUp)}
function onDown(e){canvas.focus();const p=screenToWorld(e.clientX,e.clientY),t=tokenAt(p);pointer.down=true;pointer.start={x:e.clientX,y:e.clientY};pointer.world=p;pointer.cam={...state.camera};pointer.mode=e.button===2||state.tool==="pan"?"pan":state.tool;if(pointer.mode==="select"&&t){state.selected=t.id;syncTokenForm();renderTokens();updateSelectedMove();pointer.mode=canMove(t)?"token":"pan";pointer.id=t.id;pointer.offset={x:t.x-p.x,y:t.y-p.y}}else if(pointer.mode==="fog"&&state.canEdit){state.fogDraft={x:p.x,y:p.y,width:1,height:1,label:"Area oculta"}}else if(pointer.mode==="measure"){state.measure={from:p,to:p}}else if(pointer.mode==="terrain"&&state.canEdit){pointer.terrainTouched=new Set();toggleTerrainAtWorld(p)}drawOnce()}
function onMove(e){if(!pointer.down)return;if(pointer.mode==="pan"){state.camera.x=pointer.cam.x+e.clientX-pointer.start.x;state.camera.y=pointer.cam.y+e.clientY-pointer.start.y}else if(pointer.mode==="token"){const t=state.tokens.find(x=>x.id===pointer.id),p=screenToWorld(e.clientX,e.clientY);if(t){const q=snap({x:p.x+pointer.offset.x,y:p.y+pointer.offset.y});t.x=q.x;t.y=q.y}}else if(pointer.mode==="fog"){const p=screenToWorld(e.clientX,e.clientY),a=pointer.world;state.fogDraft={x:Math.min(a.x,p.x),y:Math.min(a.y,p.y),width:Math.abs(p.x-a.x),height:Math.abs(p.y-a.y),label:"Area oculta"}}else if(pointer.mode==="measure"){state.measure.to=screenToWorld(e.clientX,e.clientY)}else if(pointer.mode==="terrain"&&state.canEdit){toggleTerrainAtWorld(screenToWorld(e.clientX,e.clientY))}drawOnce()}
function onUp(){if(!pointer.down)return;const t=state.tokens.find(x=>x.id===pointer.id),fog=state.fogDraft;pointer.down=false;state.fogDraft=null;if(pointer.mode==="token"&&t)moveToken(t).catch(e=>status(e.message,"err"));if(pointer.mode==="fog"&&fog)saveFog(fog);if(pointer.mode==="measure")setTimeout(()=>{state.measure=null;drawOnce()},1000)}
init().catch(e=>status(e.message,"err"));
